language: android
jdk: oraclejdk8

env:
  global:
    - EMULATOR_ANDROID_VERSION=24
    - ADB_INSTALL_TIMEOUT=8
before_install:
  - export ANDROID_NDK_HOME=./android-ndk-r20
  - 'if [[ ! -d "$ANDROID_NDK_HOME" ]] ;
   then
    rm -fr $ANDROID_NDK_HOME;
    curl -L https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip -O;
    unzip -oq android-ndk-r20-linux-x86_64.zip;
    ls -ltr $ANDROID_NDK_HOME;
    ls -ltr $ANDROID_NDK_HOME/platforms;
    rm android-ndk-r20-linux-x86_64.zip;
  fi'
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "84831b9409646a918e30573bab4c9c91346d8abd\n504667f4c0de7af1a06de9f4b1727b84351f2910" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager "platforms;android-28"

install: true

android:
  components:
    - tools
    - ndk-bundle

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches/
    - $HOME/.m2

before_script:
  - $ANDROID_HOME/tools/bin/sdkmanager --channel=0 "tools" "platform-tools" "build-tools;28.0.1" "platforms;android-28" "platforms;android-$EMULATOR_ANDROID_VERSION" "system-images;android-$EMULATOR_ANDROID_VERSION;default;armeabi-v7a"
  - echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -f -n test -k "system-images;android-$EMULATOR_ANDROID_VERSION;default;armeabi-v7a"
  - echo 'disk.dataPartition.size=512M' >> ~/.android/avd/test.avd/config.ini
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -verbose -show-kernel &

script:
  - ./gradlew build assembleDebug
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb logcat ActivityManager:I Reversatile:D *:S | tee logcat.log > /dev/null 2>&1 &
  - cat logcat.log | $ANDROID_NDK_HOME/ndk-stack -sym project/build/intermediates/ndkBuild/debug/obj/local > ndk-error.log
  - ./gradlew connectedCheck

after_success:

  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
  - ls -ltr
  - find . -name logcat.log
  - cat logcat.log
  - cat ndk-error.log

before_deploy:
  - echo building signed release
  - openssl aes-256-cbc -K $encrypted_03208d80b1d9_key -iv $encrypted_03208d80b1d9_iv -in keystore/zebra.jks.enc -out keystore/zebra.jks -d
  - openssl aes-256-cbc -K $encrypted_913a23d5a238_key -iv $encrypted_913a23d5a238_iv -in keystore/api-playstore.json.enc -out keystore/api-playstore.json -d
  - ./gradlew build crashlyticsUploadSymbolsRelease publishBundle -Preversatile_key_alias=${reversatile_key_alias} -Preversatile_key_password=${reversatile_key_password} -Preversatile_keystore_password=${reversatile_keystore_password}
  - ./gradlew assembleRelease
  - git status
  - find . -name *.apk

deploy:
  provider: releases
  api_key:
    secure: OzY2HHyFmcop+412mV/XXSrbqb8T6T4K5ATr8rP4YZXWnrtRU7HvAcfYkQQNvU5d+9pBA2D6nP3ZW7R9Ia/rdT/ysylJtOM3hR+8wwVNKoa8unxHzUgQgn3txxos1VxLON5vzR4lhyNpo8j+Di3Xcb5EVw/+g7HKbr7pytAkBnvAdv4vGW4B0SFwiFpHrSLlW/5uL8BKGmi/oG4sJGKNt5UE6Z0RCtj7YgesNyDwMGtMvGBXj5PdISgETCy3ZdYCRR1G7Y4Oeqfw3LAmv9C54MrFZlNdXzAbuGhEXKy8UDLD0uYWXOsxq9xpmfE3Xw79HCqqmHXfMmuf1IO3Tgit1a/aN6CWC33fH+cMt3h9C0ulGHnrUpLKNC7xlQeP66TjPDtYQYhvnAGF8Ps7yYyjpExrREsh9ShKJPVhtfWCPQQCaCygcWTUD4JLwRr4gy0d14cpOUNVIJ5ja/u+oGCy16VZ7PFeOLiZbZQ8IWrYSRh1Rdxn/9q0ac8hAlj24QwIDTbhAHh+JgRbkCxIAPiZ+bDQCkLKe6MM9Vt7H9Yox2f83cIVfPLj9bZKRb2FuLRWtXezB41pU7Hk/+AnfLyM/hyELKE8tCe8h6yQCEIB/iPiCd1SbCYmZ0gChz4egaBCAQgJXJ+mQd8XjYnrbERbG6HK/GHsH66WLQKMbwpRVKY=
  file_glob: true
  file: "./project/build/outputs/apk/release/reversatile-release-*-signed.apk"
  skip_cleanup: true
  on:
    repo: oers/reversatile
    tags: true

